ekf_filter_node_global:
  ros__parameters:
    use_sim_time: true
    frequency: 10.0
    two_d_mode: true
    publish_tf: true
    
    world_frame: map
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link

    # GPS Position
    odom0: /odometry/gps
    odom0_config: [true,  true,  false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: true

    # Bow IMU (Main Heading Source)
    imu0: /model/ripc_usv/imu_bow
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  false, false, false]
    imu0_relative: false
    imu0_qos: best_effort

    # Stern IMU (We use the less noisy IMU for the inital heading information)
    imu1: /model/ripc_usv/imu_stern
    imu1_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu1_relative: false
    imu1_qos: best_effort