navsat_transform_node:
  ros__parameters:
    use_sim_time: true
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    
    # Matching your 'ros2 param list' exactly
    publish_filtered_gps: true
    broadcast_cartesian_transform: true
    broadcast_cartesian_transform_as_parent_frame: false  # Added _frame
    
    # Frames
    map_frame: map
    utm_frame: utm
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map 
    
    # Initialization
    wait_for_datum: false
    datum: [-33.72422, 150.692, 0.0]

  qos_overrides:
      /odometry/filtered:
        subscription:
          reliability: reliable