navsat_transform_node:
  ros__parameters:
    use_sim_time: true
    wait_for_datum: false
    
    # Alignment: Gazebo North (Y) is 1.5708 rad offset from ROS North
    yaw_offset: 0.0
    magnetic_declination_radians: 0.0
    use_odometry_yaw: false
    
    publish_filtered_gps: true
    zero_altitude: true
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map