# config/bridge_config.yaml

# --- TRANSFORMS (TF) ---
- ros_topic_name: "/tf"
  gz_topic_name: "/model/ripc_usv/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# --- ODOMETRY ---
- ros_topic_name: "/model/ripc_usv/odometry"
  gz_topic_name: "/model/ripc_usv/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# --- SENSORS ---
- ros_topic_name: "/model/ripc_usv/imu_bow"
  gz_topic_name: "/model/ripc_usv/imu_bow"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS  
  publisher_reliability: "best_effort"

- ros_topic_name: "/model/ripc_usv/imu_stern"
  gz_topic_name: "/model/ripc_usv/imu_stern"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/gps/fix"
  gz_topic_name: "/model/ripc_usv/gps/fix"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS

# --- JOINTS ---
- ros_topic_name: "/joint_states"
  gz_topic_name: "/model/ripc_usv/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# --- THRUSTERS (ROS to GZ) ---
- ros_topic_name: "/ripc_usv/thrusters/left/thrust"
  gz_topic_name: "/ripc_usv/thrusters/left/thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/ripc_usv/thrusters/right/thrust"
  gz_topic_name: "/ripc_usv/thrusters/right/thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ