ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 1.0
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true

    # Frames
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Odom input
    odom0: /custom_usv/odom
    odom0_config: [true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 5
    odom0_nodelay: false

    # IMU input
    imu0: /custom_usv/imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false]
    imu0_queue_size: 50
    imu0_remove_gravitational_acceleration: true

    # GPS input → now using navsat_transform_node output
    gps0: /odometry/gps         # transformed from lat/lon
    gps0_config: [true, true, false]
    gps0_queue_size: 5
    gps0_relative: false

    publish_tf: true
    publish_acceleration: false
